name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - id: get-variable
      run: echo github.action_path is ${{github.action_path}}
      shell: bash
    - name: copy files
      run: cp ${{ github.action_path }}/module.ps1 . # share script to user
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
