name: shell-test

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  shell-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo github.action_path is ${{github.action_path}}
          echo "Run a multi-line script"
      - id: foo
        uses: ./.github/actions
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - run: ls -al
        shell: bash
      - name: show dir
        shell: bash
        run: |
          sudo apt install tree
          tree -al .
      - name: run pwsh
        shell: pwsh
        run: |
          . ./module.ps1
          Show-Calendar
          Show-Calendar3
          Show-Calendar2
